import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'








export default function Home() {

  const [loading, setLoadingClass] = useState("")
  const [result, setResult] = useState(0)
  const [lastResult, setLast] = useState("")

  const handleClick = async ()=>{
    try{
    setLoadingClass("loading")
    const res = await fetch('api/dataset')
    const json = await res.json()
    const float  = parseFloat(json.response).toFixed(2)
    setResult(float)
    setLast(json.lastResult)
    setLoadingClass("")
    }catch{
      setLoadingClass("")
      
    }
  }
 





  return (
    <>
      <Head>
        <title>Hack Crash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8791644204878853"
     crossorigin="anonymous"></script>
      </Head>
      <main className={`${styles.main}`}>
      <div style={{display:"grid", alignContent:"center", justifyContent:"center"}}>
        <h1 style={{color:"aliceblue", textAlign:"center", top:0}}>Crash Hack</h1>
        <div style={{textAlign:"center",  padding:"1em" ,width:"100%", height:"100%", display:"grid"}}>
        <h1 style={{color:"green", fontSize:"5em", color:"aliceblue"}}>{result>=1?result+"X":'1.00'}</h1>
        <div style={{width:"100px", height:"100px", borderRadius:"100%", padding:"4px", marginLeft:"25%",  background: "linear-gradient(to right, red, purple)"}} className={`buttonStart ${loading}`}>
        <div onClick={handleClick}  style={{width:"100%",  height:"100%",  display:"grid", alignContent:"center",  justifyContent:"center", color:"#fff", background:"#9ca3a9b8" ,borderRadius:"50%"}}>START</div>
        </div>

</div>
<a href="https://blaze.com/r/2BQ9QB">Clique aqui e abra sua conta Blaze</a>

Ultimo resultado:{lastResult}
        </div>      
      </main>
    </>
  )
}
